CREATE TABLE ITEM_PEDIDO 
( 
 PRECO_UNITARIO_ITEM_PED INT,  
 QUANTIDADE_ITEM_PED INT,  
 ID_ITEM_PED INT PRIMARY KEY,  
); 

CREATE TABLE PEDIDO 
( 
 ID_PED INT PRIMARY KEY,  
 DT_PED INT,  
 STATUS_PED INT,  
 VALOR_TOTAL_PED INT,  
 idITEM_PEDIDO INT,  
); 

CREATE TABLE USUARIO 
( 
 ID_USU INT PRIMARY KEY,  
 NOME_USU INT,  
 SENHA_USU INT,  
 CPF_USU INT,  
 TELEFONE_USU INT,  
 DT_CRIACAO_USU INT,  
 EMAIL_USU INT,  
 idPEDIDO INT,  
); 

CREATE TABLE PRODUTO 
( 
 NOME_PROD INT,  
 ID_PROD INT PRIMARY KEY,  
 DESCRICAO_PROD INT,  
 PRECO_PROD INT,  
 QTD_ESTOQUE_PROD INT,  
 idITEM_PEDIDO INT,  
); 

CREATE TABLE FORNECEDOR 
( 
 ID_FORNEC INT PRIMARY KEY,  
 TIPO_FORNEC INT,  
 CNPJ_FORNEC INT,  
 CPF_FORNEC INT,  
 NOME_FORNEC INT,  
 EMAIL_FORNEC INT,  
 TELEFONE_FORNEC INT,  
 idENDERECO INT,  
 idPRODUTO INT,  
); 

CREATE TABLE CATEGORIA 
( 
 DESCRICAO_CATEG INT,  
 NOME_CATEG INT,  
 ID_CATEG INT PRIMARY KEY,  
 idPRODUTO INT,  
); 

CREATE TABLE ENDERECO 
( 
 CEP_END INT,  
 ESTADO_END INT,  
 CIDADE_END INT,  
 RUA_END INT,  
 ID_END INT PRIMARY KEY,  
 COMPLEMENTO_END INT,  
 BAIRRO_END INT,  
 idUSUARIO INT,  
); 

ALTER TABLE PEDIDO ADD FOREIGN KEY(idITEM_PEDIDO) REFERENCES ITEM_PEDIDO (idITEM_PEDIDO)
ALTER TABLE USUARIO ADD FOREIGN KEY(idPEDIDO) REFERENCES PEDIDO (idPEDIDO)
ALTER TABLE PRODUTO ADD FOREIGN KEY(idITEM_PEDIDO) REFERENCES ITEM_PEDIDO (idITEM_PEDIDO)
ALTER TABLE FORNECEDOR ADD FOREIGN KEY(idENDERECO) REFERENCES ENDERECO (idENDERECO)
ALTER TABLE FORNECEDOR ADD FOREIGN KEY(idPRODUTO) REFERENCES PRODUTO (idPRODUTO)
ALTER TABLE CATEGORIA ADD FOREIGN KEY(idPRODUTO) REFERENCES PRODUTO (idPRODUTO)
ALTER TABLE ENDERECO ADD FOREIGN KEY(idUSUARIO) REFERENCES USUARIO (idUSUARIO)
